<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vendas.Domain\Vendas.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\CatalogoCommands\CategoriaCommands\AtivarCategoria\" />
    <Folder Include="Commands\CatalogoCommands\CategoriaCommands\CriarCategoria\" />
    <Folder Include="Commands\CatalogoCommands\CategoriaCommands\InativarCategoria\" />
    <Folder Include="Commands\CatalogoCommands\CategoriaCommands\RenomearCategoria\" />
    <Folder Include="Commands\CatalogoCommands\ClientesCommands\" />
  </ItemGroup>

</Project>
